Крестик удаления истории
IT3G/work-calendar pull request #118
Opened 2020-02-18 17:24 UTC by urdenko

2020-02-18 20:25 UTC, klimentru1986 commented on backend/src/work-calendar/guards/task-delete.guard.ts
> +export class TaskDeleteGuard implements CanActivate {
Предложил бы сделать 2 гварда.

- Один `isAdmin` чтоб можно было переиспользовать.
- Второй  для проверки дня

2020-02-18 20:31 UTC, klimentru1986 commented on frontend/src/app/core/store/context-store.service.ts
> -    return this.currentDate;
* `asObservable` метод который не рекомендуется использовать ([подробности](https://stackoverflow.com/questions/48935584/observable-vs-subject-and-asobservable?answertab=active#tab-top)). Если метод возвращает Observable, то методы сабджекта не будут доступны.

* Не нужно момент заворачивать в момент еще раз

2020-02-18 20:31 UTC, klimentru1986 commented on frontend/src/app/core/store/context-store.service.ts
> -    return this.currentDate.value;
Не надо повторно оборачивать в `moment()`

2020-02-19 06:13 UTC, urdenko commented on backend/src/work-calendar/guards/task-delete.guard.ts
> +export class TaskDeleteGuard implements CanActivate {
Каждый гард дергает базу на получении сущности таски, соответсвено два гарда = 1 лишний запрос

2020-02-19 06:26 UTC, urdenko commented on backend/src/work-calendar/guards/task-delete.guard.ts
> +export class TaskDeleteGuard implements CanActivate {
поправка, для админа не нужен допзапрос, сейчас поправлю

2020-02-19 09:17 UTC, urdenko commented on backend/src/work-calendar/guards/task-delete.guard.ts
> +export class TaskDeleteGuard implements CanActivate {
done

2020-02-19 09:17 UTC, urdenko commented on frontend/src/app/core/store/context-store.service.ts
> -    return this.currentDate.value;
done

2020-02-19 09:17 UTC, urdenko commented on frontend/src/app/core/store/context-store.service.ts
> -    return this.currentDate;
done

2020-02-19 11:40 UTC, klimentru1986 requested changes

2020-02-19 11:40 UTC, klimentru1986 commented on frontend/src/app/core/store/context-store.service.ts
> -    this.currentDate.next(date);
Не надо повторно оборачивать в `moment()`

2020-02-19 11:40 UTC, klimentru1986 commented on frontend/src/app/core/store/context-store.service.ts
> +  private getNewEmployeeState(employee?: Employee): Employee | null {
Данный метод:
* Усложняется читаемость кода. 
* Появляется лишний мапер в том месте в котором разработчик его не ждет.
* Отрицательно сказывается на производительности (хотя это уже мелочи)

По факту вряд-ли кто-то захочет мутабельно изменить справочники. А пользователь меняется только через реактивную форму, которая возвращает новый объект. 

Данный код больше похож на борьбу с ветряными мельницами, чем на реальную защиту.

Пожалуйста, верни как было.

2020-02-19 11:40 UTC, klimentru1986 commented on frontend/src/app/core/store/tasks-store.service.ts
> +    return this.tasks$.asObservable().pipe(map(tasks => tasks.map(task => <TaskModel>{ ...task })));
`asObservable` не нужен

2020-02-19 11:40 UTC, klimentru1986 commented on frontend/src/app/core/store/tasks-store.service.ts
> +    this.tasks$.next(val.map(task => <TaskModel>{ ...task }));
Тут тоже просьба вернуть как было.

2020-02-19 11:40 UTC, klimentru1986 commented on frontend/src/app/presense/components/presence-history/presence-history.component.html
> +      *ngIf="canDeleteCalendarTask(task)"
Использование метода в шаблоне плохая практика. Лучше делать Pipe.

2020-02-19 11:40 UTC, klimentru1986 commented on frontend/src/app/presense/components/presence-page/presence-page.component.ts
> +            this.currentUser = this.contextStoreService.getCurrentUser();
currentUser из контекста можно передать через asyncPipe без лишних тапов

2020-02-19 11:40 UTC, klimentru1986 commented on frontend/src/app/shared/models/employee-project.model.ts
> +/** Модель Проекта в котором участвует Сотрудник */
Это старая модель которую предполагалось выпиливать, так что тогда лучше сразу выпилить.

2020-02-19 11:40 UTC, klimentru1986 commented on frontend/src/app/core/store/context-store.service.ts
> +      employee.subdivision && <DictionaryModel>{ _id: employee.subdivision._id, name: employee.subdivision.name };
Дли инфо. Лучше использовать вместо дженериков синтаксис `as`
https://stackoverflow.com/a/44202312/8931009

2020-02-19 11:40 UTC, klimentru1986 commented on frontend/src/app/core/store/context-store.service.ts
> +    return this.currentDate.asObservable().pipe(map(currentDate => moment(currentDate)));
* `asObservable` метод который не рекомендуется использовать ([подробности](https://stackoverflow.com/questions/48935584/observable-vs-subject-and-asobservable?answertab=active#tab-top)). Если метод возвращает Observable, то методы сабджекта не будут доступны.

* Не нужно момент заворачивать в момент еще раз

2020-02-19 11:42 UTC, urdenko commented on frontend/src/app/core/store/context-store.service.ts
> +  private getNewEmployeeState(employee?: Employee): Employee | null {
done

2020-02-19 11:44 UTC, urdenko commented on frontend/src/app/shared/models/employee-project.model.ts
> +/** Модель Проекта в котором участвует Сотрудник */
Для выпиливания нужны процедуры на БД, иначе мусор будет храниться

2020-02-19 13:09 UTC, merged