Firebase
IT3G/work-calendar pull request #13
Opened 2019-02-11 15:55 UTC by glotovdi

2019-02-19 15:02 UTC, enrey requested changes

2019-02-19 15:02 UTC, enrey commented on src/app/description/description.component.html
> +  <table mat-table
Это все-таки отдельный компонент, ala description-history.component.ts

2019-02-19 15:02 UTC, enrey commented on src/app/shared/services/crud.service.ts
> +export class CrudService {
Это по факту реализация Repository для Firebase (они успели появиться :), сейчас есть один "in-memory" для Tasks (tasks-repository.service.ts), этот соответственно должен стать tasks-repository-firebase.service.ts и теперь использоваться по умолчанию вместо старого (старый пригодится для тестов)
Repository забирает данные откуда угодно (firebase, local in-memory array и т.д.) и "диспатчит" их в стор.

2019-02-19 15:04 UTC, enrey commented
Ну и билд упал..

2019-02-21 15:21 UTC, glotovdi commented on src/app/description/description.component.html
> +  <table mat-table
done

2019-02-22 15:50 UTC, glotovdi commented on src/app/shared/services/crud.service.ts
> +export class CrudService {
done

2019-02-23 08:14 UTC, merged